
import { Language, QuizQuestion, Dua } from './types.ts';

export const WALLPAPERS = [
  "https://images.unsplash.com/photo-1591604129939-f1efa4d9f7fa?q=80&w=2070&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1542816417-0983c9c9ad53?q=80&w=2070&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1564182842519-8a3b2af3e228?q=80&w=2070&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1519817650390-64a93db51149?q=80&w=2070&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1523733593134-a820d071464e?q=80&w=2070&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1590075865003-e48277faf551?q=80&w=2070&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=80&w=2070&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1518005020453-1bb74470290b?q=80&w=2070&auto=format&fit=crop"
];

export const TRANSLATIONS = {
  ar: {
    home: 'الرئيسية', quiz: 'المسابقة', azkar: 'الأذكار', wird: 'الورد', settings: 'الإعدادات',
    prayerTimes: 'مواقيت الصلاة', nextPrayer: 'الصلاة القادمة', weather: 'الطقس اليوم',
    dailyDua: 'دعاء اليوم', startQuiz: 'ابدأ المسابقة', points: 'نقاط', language: 'اللغة',
    theme: 'المظهر', darkMode: 'الوضع الليلي', lightMode: 'الوضع النهاري', appName: 'Osey Islamk',
    score: 'النتيجة', congrats: 'أحسنت!', tryAgain: 'حاول مرة أخرى'
  },
  en: {
    home: 'Home', quiz: 'Quiz', azkar: 'Azkar', wird: 'Daily Wird', settings: 'Settings',
    prayerTimes: 'Prayer Times', nextPrayer: 'Next Prayer', weather: 'Weather',
    dailyDua: 'Daily Dua', startQuiz: 'Start Quiz', points: 'Points', language: 'Language',
    theme: 'Theme', darkMode: 'Dark Mode', lightMode: 'Light Mode', appName: 'Osey Islamk',
    score: 'Score', congrats: 'Congrats!', tryAgain: 'Try Again'
  },
  fr: {
    home: 'Accueil', quiz: 'Quiz', azkar: 'Azkar', wird: 'Wird', settings: 'Settings',
    prayerTimes: 'Horaires', nextPrayer: 'Suivante', weather: 'Météo',
    dailyDua: 'Doua du jour', startQuiz: 'Démarrer', points: 'Points', language: 'Langue',
    theme: 'Thème', darkMode: 'Sombre', lightMode: 'Clair', appName: 'Osey Islamk',
    score: 'Score', congrats: 'Bravo!', tryAgain: 'Réessayer'
  }
};

const BASE_QUESTIONS: QuizQuestion[] = [
  { id: 1, question: "من هو أول من أسلم من الرجال؟", options: ["أبو بكر الصديق", "علي بن أبي طالب", "عمر بن الخطاب", "عثمان بن عفان"], correctAnswer: 0 },
  { id: 2, question: "ما هي أطول سورة في القرآن الكريم؟", options: ["آل عمران", "البقرة", "النساء", "المائدة"], correctAnswer: 1 },
  { id: 3, question: "كم عدد أركان الإسلام؟", options: ["ثلاثة", "أربعة", "خمسة", "ستة"], correctAnswer: 2 },
  { id: 4, question: "ما هي السورة التي تسمى عروس القرآن؟", options: ["يس", "الرحمن", "الواقعة", "الملك"], correctAnswer: 1 },
  { id: 5, question: "من هو الملقب بذي النورين؟", options: ["عمر بن الخطاب", "علي بن أبي طالب", "عثمان بن عفان", "خالد بن الوليد"], correctAnswer: 2 },
  { id: 6, question: "كم عدد سور القرآن الكريم؟", options: ["110", "114", "118", "120"], correctAnswer: 1 },
  { id: 7, question: "من هي أم المساكين من زوجات النبي؟", options: ["خديجة", "عائشة", "زينب بنت خزيمة", "حفصة"], correctAnswer: 2 },
  { id: 8, question: "في أي شهر نزل القرآن الكريم؟", options: ["رجب", "شعبان", "رمضان", "شوال"], correctAnswer: 2 },
  { id: 9, question: "ما هي القبلة الأولى للمسلمين؟", options: ["الكعبة", "المسجد الأقصى", "المسجد النبوي", "قباء"], correctAnswer: 1 },
  { id: 10, question: "من هو النبي الذي ابتلعه الحوت؟", options: ["يونس", "أيوب", "موسى", "إبراهيم"], correctAnswer: 0 },
  { id: 11, question: "كم عدد أركان الإيمان؟", options: ["خمسة", "ستة", "سبعة", "أربعة"], correctAnswer: 1 },
  { id: 12, question: "من هو خادم الرسول صلى الله عليه وسلم؟", options: ["أنس بن مالك", "بلال بن رباح", "زيد بن حارثة", "ابن مسعود"], correctAnswer: 0 },
  { id: 13, question: "ما هي أقصر سورة في القرآن الكريم؟", options: ["الإخلاص", "العصر", "الكوثر", "الناس"], correctAnswer: 2 },
  { id: 14, question: "من هو النبي الملقب بكليم الله؟", options: ["عيسى", "موسى", "إبراهيم", "نوح"], correctAnswer: 1 },
  { id: 15, question: "ما هو اسم ناقة الرسول صلى الله عليه وسلم؟", options: ["القصواء", "الشهباء", "الخضراء", "العصماء"], correctAnswer: 0 },
  { id: 16, question: "كم عدد سنوات الدعوة في مكة؟", options: ["10 سنوات", "13 سنة", "15 سنة", "23 سنة"], correctAnswer: 1 },
  { id: 17, question: "ما هو اسم بئر الماء في الحرم المكي؟", options: ["بئر بدر", "بئر زمزم", "بئر غرس", "بئر الأريان"], correctAnswer: 1 },
  { id: 18, question: "من هو الملك الموكل بالوحي؟", options: ["ميكائيل", "إسرافيل", "جبريل", "مالك"], correctAnswer: 2 },
  { id: 19, question: "في أي غزوة كُسرت بيضة النبي؟", options: ["بدر", "أحد", "الخندق", "حنين"], correctAnswer: 1 },
  { id: 20, question: "ما هي السورة التي بدأت بدون بسملة؟", options: ["الفاتحة", "التوبة", "يس", "الكهف"], correctAnswer: 1 },
  { id: 21, question: "من هو أول مؤذن في الإسلام؟", options: ["أبو بكر", "بلال بن رباح", "عمار بن ياسر", "سعد بن أبي وقاص"], correctAnswer: 1 },
  { id: 22, question: "ما هو لقب حمزة بن عبد المطلب؟", options: ["سيف الله", "أسد الله", "ذو الجناحين", "أمين الأمة"], correctAnswer: 1 },
  { id: 23, question: "كم عدد السجدات في القرآن الكريم؟", options: ["12 سجدة", "14 سجدة", "15 سجدة", "10 سجدات"], correctAnswer: 2 },
  { id: 24, question: "من هو النبي الذي بنى السفينة؟", options: ["هود", "نوح", "صالح", "شعيب"], correctAnswer: 1 },
  { id: 25, question: "ما هو الاسم الحقيقي لأبي بكر؟", options: ["عبد الله بن عثمان", "عمر بن الخطاب", "عثمان بن عفان", "عبد الرحمن"], correctAnswer: 0 },
  { id: 26, question: "ما هي السورة التي تعدل ثلث القرآن؟", options: ["الفاتحة", "الإخلاص", "يس", "آية الكرسي"], correctAnswer: 1 },
  { id: 27, question: "من هو النبي الذي كان يبرئ الأكمه والأبرص؟", options: ["موسى", "عيسى", "داود", "سليمان"], correctAnswer: 1 },
  { id: 28, question: "ما هي مهنة النبي قبل النبوة؟", options: ["الحدادة", "النجارة", "الرعي والتجارة", "الزراعة"], correctAnswer: 2 },
  { id: 29, question: "من هو الصحابي الذي تستحي منه الملائكة؟", options: ["أبو بكر", "عمر", "عثمان بن عفان", "علي"], correctAnswer: 2 },
  { id: 30, question: "ما هو أطول يوم في حياة المسلم؟", options: ["الجمعة", "يوم العيد", "يوم القيامة", "يوم عرفة"], correctAnswer: 2 },
  { id: 31, question: "كم عدد أبناء النبي محمد؟", options: ["5", "6", "7", "8"], correctAnswer: 2 },
  { id: 32, question: "من هو الملقب بـ الفاروق؟", options: ["أبو بكر", "عمر بن الخطاب", "خالد بن الوليد", "حمزة"], correctAnswer: 1 },
  { id: 33, question: "ما هي السورة التي تسمى قلب القرآن؟", options: ["البقرة", "يس", "الرحمن", "الواقعة"], correctAnswer: 1 },
  { id: 34, question: "في أي سنة هجرية كانت غزوة بدر؟", options: ["1 هـ", "2 هـ", "3 هـ", "4 هـ"], correctAnswer: 1 },
  { id: 35, question: "من هو النبي الذي أُعطي شطر الجمال؟", options: ["يوسف", "داود", "سليمان", "يحيى"], correctAnswer: 0 },
  { id: 36, question: "ما هو اسم خازن الجنة؟", options: ["مالك", "رضوان", "منكر", "نكير"], correctAnswer: 1 },
  { id: 37, question: "ما هو اسم خازن النار؟", options: ["رضوان", "مالك", "إسرافيل", "عزرائيل"], correctAnswer: 1 },
  { id: 38, question: "كم عدد الخلفاء الراشدين؟", options: ["3", "4", "5", "6"], correctAnswer: 1 },
  { id: 39, question: "من هو النبي الذي صام عن الكلام 3 أيام؟", options: ["إسماعيل", "زكريا", "لوط", "إدريس"], correctAnswer: 1 },
  { id: 40, question: "ما هي أعظم آية في القرآن الكريم؟", options: ["آية الكرسي", "آخر البقرة", "الفاتحة", "آية الدين"], correctAnswer: 0 },
  { id: 41, question: "من هو النبي الذي سخر الله له الريح؟", options: ["داود", "سليمان", "أيوب", "إلياس"], correctAnswer: 1 },
  { id: 42, question: "ما هي دار الإسلام الأولى للهجرة؟", options: ["المدينة", "الحبشة", "مكة", "الطائف"], correctAnswer: 1 },
  { id: 43, question: "من هو الصحابي أمين الأمة؟", options: ["أبو عبيدة", "معاذ بن جبل", "سعد بن معاذ", "طلحة"], correctAnswer: 0 },
  { id: 44, question: "ما هي السورة التي ذكرت فيها البسملة مرتين؟", options: ["البقرة", "النمل", "النحل", "هود"], correctAnswer: 1 },
  { id: 45, question: "من هو النبي ذو النون؟", options: ["يونس", "إسماعيل", "إسحاق", "يعقوب"], correctAnswer: 0 },
  { id: 46, question: "ما هو اسم الجبل الذي استقرت عليه سفينة نوح؟", options: ["الطور", "الجودي", "عرفات", "أحد"], correctAnswer: 1 },
  { id: 47, question: "كم عدد أولي العزم من الرسل؟", options: ["3", "4", "5", "7"], correctAnswer: 2 },
  { id: 48, question: "من هو النبي الذي رفعه الله إليه؟", options: ["إبراهيم", "عيسى", "موسى", "يحيى"], correctAnswer: 1 },
  { id: 49, question: "ما هي الصلاة التي لا ركوع فيها ولا سجود؟", options: ["الكسوف", "الجنازة", "الاستسقاء", "الوتر"], correctAnswer: 1 },
  { id: 50, question: "من هو الصحابي الذي اهتز لموته العرش؟", options: ["عمر", "سعد بن معاذ", "علي", "خالد"], correctAnswer: 1 },
  { id: 51, question: "من هي أول شهيدة في الإسلام؟", options: ["خديجة", "سمية بنت خياط", "فاطمة", "عائشة"], correctAnswer: 1 },
  { id: 52, question: "كم عدد أركان الإحسان؟", options: ["ركن واحد", "ركنان", "ثلاثة", "أربعة"], correctAnswer: 0 },
  { id: 53, question: "من هو النبي الذي بعث إلى قوم ثمود؟", options: ["هود", "صالح", "شعيب", "لوط"], correctAnswer: 1 },
  { id: 54, question: "ما هو الاسم الآخر لسورة الفاتحة؟", options: ["السبع المثاني", "المنجية", "الواقعة", "الفرقان"], correctAnswer: 0 },
  { id: 55, question: "من هو الملقب بشاعر الرسول؟", options: ["حسان بن ثابت", "جرير", "الفرزدق", "كعب بن مالك"], correctAnswer: 0 },
  { id: 56, question: "ما هي أطول آية في القرآن؟", options: ["آية الكرسي", "آية الدين", "آية المداينة", "آية الربا"], correctAnswer: 1 },
  { id: 57, question: "كم عدد طبقات جهنم؟", options: ["5", "6", "7", "8"], correctAnswer: 2 },
  { id: 58, question: "من هو النبي الملقب بـ إسرائيل؟", options: ["يعقوب", "إسماعيل", "يوسف", "إسحاق"], correctAnswer: 0 },
  { id: 59, question: "ما هي السورة التي تسمى الفاضحة؟", options: ["المنافقون", "التوبة", "الأحزاب", "الفتح"], correctAnswer: 1 },
  { id: 60, question: "من هو أول من صام؟", options: ["آدم عليه السلام", "نوح عليه السلام", "إبراهيم عليه السلام", "محمد صلى الله عليه وسلم"], correctAnswer: 0 },
  { id: 61, question: "ما هو لقب جعفر بن أبي طالب؟", options: ["الطيار", "الفاروق", "الصديق", "ذو النورين"], correctAnswer: 0 },
  { id: 62, question: "كم عدد سنوات خلافة أبو بكر؟", options: ["سنتان", "3 سنوات", "4 سنوات", "5 سنوات"], correctAnswer: 0 },
  { id: 63, question: "ما هي المعجزة الكبرى للنبي محمد؟", options: ["انشقاق القمر", "القرآن الكريم", "الإسراء والمعراج", "نبع الماء"], correctAnswer: 1 },
  { id: 64, question: "من هو الصحابي الذي جمع الناس على مصحف واحد؟", options: ["عمر", "أبو بكر", "عثمان بن عفان", "علي"], correctAnswer: 2 },
  { id: 65, question: "ما هي السورة التي تسمى بني إسرائيل؟", options: ["الكهف", "الإسراء", "مريم", "طه"], correctAnswer: 1 },
  { id: 66, question: "من هو النبي الذي ألان الله له الحديد؟", options: ["سليمان", "داود", "موسى", "إبراهيم"], correctAnswer: 1 },
  { id: 67, question: "كم عدد التكبيرات في الركعة الأولى لصلاة العيد؟", options: ["5", "6", "7", "8"], correctAnswer: 2 },
  { id: 68, question: "ما هي عاصمة الدولة الإسلامية في عهد علي؟", options: ["المدينة", "مكة", "الكوفة", "دمشق"], correctAnswer: 2 },
  { id: 69, question: "من هي زوجة النبي التي كانت ابنة عدو الله حيي بن أخطب؟", options: ["صفية", "جورية", "ميمونة", "سودة"], correctAnswer: 0 },
  { id: 70, question: "ما هو اسم خيل النبي الذي سبق في الرهان?", options: ["السكب", "المرتجز", "اللزاز", "الظرب"], correctAnswer: 0 },
  { id: 71, question: "من هو الصحابي الذي قتل أبا جهل؟", options: ["معاذ ومعوذ", "عمر وعلي", "حمزة وخالد", "بلال وعمار"], correctAnswer: 0 },
  { id: 72, question: "ما هي السورة التي تنتهي جميع آياتها بحرف الراء؟", options: ["العصر", "الكوثر", "القدر", "القمر"], correctAnswer: 1 },
  { id: 73, question: "كم كان عمر النبي عندما توفيت أمه؟", options: ["4 سنوات", "6 سنوات", "8 سنوات", "10 سنوات"], correctAnswer: 1 },
  { id: 74, question: "من هو الملقب بـ حبر الأمة؟", options: ["عبد الله بن عباس", "عبد الله بن مسعود", "عبد الله بن عمر", "عبد الله بن الزبير"], correctAnswer: 0 },
  { id: 75, question: "ما هي السورة التي تسمى الحائلة؟", options: ["الكهف", "يس", "الرحمن", "الواقعة"], correctAnswer: 0 },
  { id: 76, question: "من هو أول من جهر بالقرآن في مكة؟", options: ["أبو بكر", "عمر", "ابن مسعود", "علي"], correctAnswer: 2 },
  { id: 77, question: "كم عدد أجنحة جبريل عليه السلام؟", options: ["100", "300", "600", "1000"], correctAnswer: 2 },
  { id: 78, question: "ما هو اسم سيف النبي؟", options: ["ذو الفقار", "البتار", "الصارم", "المهند"], correctAnswer: 0 },
  { id: 79, question: "من هو النبي الذي نزل عليه الزبور؟", options: ["موسى", "عيسى", "داود", "سليمان"], correctAnswer: 2 },
  { id: 80, question: "ما هي الغزوة التي هزم فيها المسلمون في البداية؟", options: ["أحد", "حنين", "تبوك", "الخندق"], correctAnswer: 1 },
  { id: 81, question: "كم مكث يونس في بطن الحوت؟", options: ["3 أيام", "7 أيام", "40 يوماً", "غير محدد بدقة"], correctAnswer: 3 },
  { id: 82, question: "من هو أول مولود في الإسلام بالمدينة؟", options: ["عبد الله بن الزبير", "إبراهيم بن محمد", "الحسن بن علي", "أسامة بن زيد"], correctAnswer: 0 },
  { id: 83, question: "ما هي السورة التي تسمى الساهرة؟", options: ["النازعات", "النبأ", "التكوير", "الانفطار"], correctAnswer: 0 },
  { id: 84, question: "من هو الصحابي الذي لُقب بـ ذي البجادين؟", options: ["عبد الله المزني", "سعد بن عبادة", "معاذ بن جبل", "أبو ذر"], correctAnswer: 0 },
  { id: 85, question: "كم عدد المهاجرين في الهجرة الأولى للحبشة؟", options: ["10", "12", "16", "20"], correctAnswer: 2 },
  { id: 86, question: "ما هي أقدس بقعة على وجه الأرض؟", options: ["مكة", "المدينة", "بيت المقدس", "سيناء"], correctAnswer: 0 },
  { id: 87, question: "من هو النبي الذي سجدت له النجوم والشمس والقمر؟", options: ["يوسف", "يعقوب", "إسماعيل", "إسحاق"], correctAnswer: 0 },
  { id: 88, question: "ما هي السورة التي تسمى المانعة؟", options: ["الملك", "الكهف", "يس", "الرحمن"], correctAnswer: 0 },
  { id: 89, question: "من هو الصحابي الذي قتله الجن؟", options: ["سعد بن عبادة", "سعد بن معاذ", "سعد بن وقاص", "سعد بن زيد"], correctAnswer: 0 },
  { id: 90, question: "كم عدد الرسل الذين ذكروا في القرآن؟", options: ["20", "25", "30", "35"], correctAnswer: 1 },
  { id: 91, question: "ما هو اسم أم النبي محمد؟", options: ["آمنة بنت وهب", "حليمة السعدية", "فاطمة بنت أسد", "سودة بنت زمعة"], correctAnswer: 0 },
  { id: 92, question: "من هو النبي الذي نزل عليه الإنجيل؟", options: ["موسى", "عيسى", "يحيى", "زكريا"], correctAnswer: 1 },
  { id: 93, question: "ما هي السورة التي ذكر فيها النمل؟", options: ["النحل", "النمل", "العنكبوت", "الفيل"], correctAnswer: 1 },
  { id: 94, question: "كم عدد التابعين؟", options: ["آلاف", "مئات", "عشرة", "غير محصور"], correctAnswer: 3 },
  { id: 95, question: "من هو النبي الذي كان يعمل نجاراً؟", options: ["زكريا", "يحيى", "عيسى", "موسى"], correctAnswer: 0 },
  { id: 96, question: "ما هي السورة التي تسمى القتال؟", options: ["الأنفال", "التوبة", "محمد", "الفتح"], correctAnswer: 2 },
  { id: 97, question: "من هو الصحابي الذي كان يسمى غسيل الملائكة؟", options: ["حنظلة بن أبي عامر", "سعد بن معاذ", "جعفر بن أبي طالب", "زيد بن حارثة"], correctAnswer: 0 },
  { id: 98, question: "كم عدد غزوات النبي؟", options: ["25", "27", "29", "31"], correctAnswer: 1 },
  { id: 99, question: "ما هي السورة التي تسمى المصابيح؟", options: ["فصلت", "يس", "الواقعة", "الملك"], correctAnswer: 0 },
  { id: 100, question: "من هو النبي الذي قبضت روحه في السماء الرابعة؟", options: ["إدريس", "إبراهيم", "موسى", "عيسى"], correctAnswer: 0 }
];

export const QUIZ_DATA = BASE_QUESTIONS;

export const DUAS: Dua[] = [
  { id: 1, title: "أذكار الصباح", content: "أصبحنا وأصبح الملك لله، والحمد لله، لا إله إلا الله وحده لا شريك له...", category: "morning" },
  { id: 2, title: "أذكار المساء", content: "أمسينا وأمسى الملك لله، والحمد لله، لا إله إلا الله وحده لا شريك له...", category: "evening" },
  { id: 3, title: "دعاء السفر", content: "سُبْحَانَ الَّذِي سَخَّرَ لَنَا هَذَا وَمَا كُنَّا لَهُ مُقْرِنِينَ وَإِنَّا إِلَى رَبِّنَا لَمُنْقَلِبُونَ", category: "travel" },
  { id: 4, title: "أذكار الاستيقاظ", content: "الحمد لله الذي أحيانا بعد ما أماتنا وإليه النشور", category: "sleep" },
  { id: 5, title: "دعاء دخول المسجد", content: "اللهم افتح لي أبواب رحمتك", category: "prayer" },
  { id: 6, title: "أذكار النوم", content: "باسمك اللهم أموت وأحيا", category: "sleep" }
];
